name = "Homestead"
version = "1.2.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6b2129bcbf960b5ad33cb2c068ed58c469e3060fcdc9b33b077aa1e3ed01aab"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
