name = "Homestead"
version = "1.2.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34b055bbebcf1b886875c3a961701afbb985fabade5fd3ef66656c1a0d0f9aac"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
