name = "Homestead"
version = "1.2.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b58f85917e3c97bac9114dc7f51baf62d24fdd98f431ef5722a2240b407c5d36"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
