name = "Homestead"
version = "1.2.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcb742361fda6c65a8ea52eb7497c7c0ee9d50a0791474f3a4e9f8495ba35b8c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
